export default {
  container: {},
  frame: { element: 'frame' },
  scope: { element: 'scope' },
  slide: { element: 'slide' },
  slideActive: { element: 'slide', modifier: 'active' },
  slideVisible: { element: 'slide', modifier: 'visible' },
  arrows: { element: 'arrow' },
  arrowsButton: { element: ['arrow', 'button'] },
  arrowsButtonActive: { element: ['arrow', 'button'], modifier: 'active' },
  arrowsButtonDisabled: { element: ['arrow', 'button'], modifier: 'disabled' },
  arrowsButtonPrevious: { element: ['arrow', 'button'], modifier: 'previous' },
  arrowsButtonNext: { element: ['arrow', 'button'], modifier: 'next' },
  arrowsIcon: { element: ['arrow', 'icon'] },
  count: { element: 'count' },
  countCurrent: { element: ['count', 'current'] },
  countDivider: { element: ['count', 'divider'] },
  countTotal: { element: ['count', 'total'] },
  pagination: { element: 'pagination' },
  paginationButton: { element: ['pagination', 'button'] },
  paginationButtonActive: {
    element: ['pagination', 'button'],
    modifier: 'active',
  },
  paginationButtonText: { element: ['pagination', 'button', 'text'] },
  horizontal: { modifier: 'horizontal' },
  vertical: { modifier: 'vertical' },
  responsive: { modifier: 'responsive' },
  init: { modifier: 'init' },
  animating: { modifier: 'animating' },
  playing: { modifier: 'playing' },
  swiping: { modifier: 'swiping' },
};
